# Generated by Django 5.2.5 on 2025-08-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_offer_offeritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="api.supplier",
            ),
        ),
    ]
