# Generated by Django 5.2.5 on 2025-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_expense_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="converted_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
