# Generated by Django 5.2.5 on 2025-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_bankaccount_currency_payment_converted_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
