# Generated by Django 5.2.6 on 2025-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_salereturn_salereturnitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Your Company Name", max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Info",
            },
        ),
    ]
