# Generated by Django 5.2.6 on 2025-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_companyinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("USD", "United States Dollar"),
                            ("EUR", "Euro"),
                            ("KZT", "Kazakhstani Tenge"),
                            ("TRY", "Turkish Lira"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Settings",
            },
        ),
    ]
