# Generated by Django 5.2.6 on 2025-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_companyinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="original_amount",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="currency",
            new_name="original_currency",
        ),
        migrations.AddField(
            model_name="purchase",
            name="converted_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchase",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchase",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchase",
            name="original_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="converted_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="original_currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
