# Generated by Django 5.2.6 on 2025-09-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_companysettings"),
        ("api", "0016_rename_amount_payment_original_amount_and_more"),
    ]

    operations = []
