# Generated by Django 5.2.5 on 2025-09-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_companysettings"),
        ("api", "0016_rename_amount_payment_original_amount_and_more"),
    ]

    operations = []
