# Generated by Django 5.2.6 on 2025-09-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_merge_20250907_0323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="api.supplier",
            ),
        ),
    ]
