# Generated by Django 5.2.6 on 2025-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_expense_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="supplier_images/"
            ),
        ),
    ]
