# Generated by Django 5.2.5 on 2025-09-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_merge_20250906_1815"),
        ("api", "0018_alter_expense_supplier"),
    ]

    operations = []
