# Generated by Django 5.2.6 on 2025-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_supplier_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
