# Generated by Django 5.2.5 on 2025-09-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_merge_20250908_0024"),
        ("api", "0020_supplier_currency"),
    ]

    operations = []
