# Generated by Django 5.2.6 on 2025-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_supplier_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="account_converted_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="account_exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
