# Generated by Django 5.2.5 on 2025-09-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_merge_0019_merge_20250908_0024_0020_supplier_currency"),
        ("api", "0021_payment_account_converted_amount_and_more"),
    ]

    operations = []
