# Generated by Django 5.2.5 on 2025-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_merge_20250912_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="account_exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
