# Generated by Django 5.2.6 on 2025-09-24 07:21

from decimal import Decimal

from django.db import migrations, models


def create_default_currencies(apps, schema_editor):
    Currency = apps.get_model('api', 'Currency')
    defaults = [
        ('USD', 'United States Dollar', Decimal('1')),
        ('EUR', 'Euro', Decimal('1')),
        ('KZT', 'Kazakhstani Tenge', Decimal('1')),
        ('TRY', 'Turkish Lira', Decimal('1')),
    ]
    for code, name, rate in defaults:
        Currency.objects.update_or_create(
            code=code,
            defaults={'name': name, 'exchange_rate': rate},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_bankaccount_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(create_default_currencies, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="bankaccounttransaction",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="base_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="customer",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="original_currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="original_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="sale",
            name="original_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
