# Generated by Django 5.2.6 on 2025-09-24 08:11

from decimal import Decimal

from django.db import migrations, models


def populate_expense_currency_fields(apps, schema_editor):
    Expense = apps.get_model('api', 'Expense')
    Supplier = apps.get_model('api', 'Supplier')
    BankAccount = apps.get_model('api', 'BankAccount')

    supplier_currencies = dict(
        Supplier.objects.values_list('id', 'currency')
    )
    account_currencies = dict(
        BankAccount.objects.values_list('id', 'currency')
    )

    for expense in Expense.objects.all().iterator():
        original_currency = (expense.original_currency or '').strip().upper()
        if not original_currency:
            if expense.supplier_id:
                original_currency = (
                    (supplier_currencies.get(expense.supplier_id) or '').strip().upper()
                )
            if not original_currency and expense.account_id:
                original_currency = (
                    (account_currencies.get(expense.account_id) or '').strip().upper()
                )
            if not original_currency:
                original_currency = 'USD'

        amount = expense.amount or Decimal('0')

        Expense.objects.filter(pk=expense.pk).update(
            original_amount=amount,
            original_currency=original_currency,
            exchange_rate=Decimal('1'),
            converted_amount=amount,
            account_exchange_rate=Decimal('1'),
            account_converted_amount=amount,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_currency_alter_bankaccount_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="account_converted_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="expense",
            name="account_exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="converted_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="expense",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="expense",
            name="original_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.RunPython(populate_expense_currency_fields, migrations.RunPython.noop),
    ]
