# Generated by Django 5.2.5 on 2025-09-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_bankaccount_category_and_more"),
        ("api", "0023_alter_payment_account_exchange_rate_and_more"),
    ]

    operations = []
