# Generated by Django 5.2.5 on 2025-09-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_currency_alter_bankaccount_currency_and_more"),
        ("api", "0024_merge_20250917_1510"),
    ]

    operations = []
