# Generated by Django 5.2.7 on 2025-10-05 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_warehouse_purchaseitem_warehouse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sale_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
