# Generated by Django 5.2.5 on 2025-09-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_expense_account_converted_amount_and_more"),
        ("api", "0025_merge_20250924_1346"),
    ]

    operations = []
