# Generated by Django 5.2.5 on 2025-09-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_warehouse_purchaseitem_warehouse_and_more"),
        ("api", "0026_merge_20250924_1512"),
    ]

    operations = []
