# Generated by Django 5.2.5 on 2025-10-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_sale_sale_date"),
        ("api", "0027_merge_20250924_1638"),
    ]

    operations = []
