# Generated by Django 5.2.7 on 2025-10-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_accountinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="seat_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="user_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
