# Generated by Django 5.2.5 on 2025-10-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_merge_20251007_1915"),
        ("api", "0030_accountinvitation"),
    ]

    operations = []
