# Generated by Django 5.2.5 on 2025-10-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_merge_0028_merge_20251007_1915_0030_accountinvitation"),
        ("api", "0031_subscription_billing_cycle_subscription_seat_limit_and_more"),
    ]

    operations = []
