# Generated by Django 5.2.7 on 2025-10-31 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_subscription_billing_cycle_subscription_seat_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_number__isnull", False)),
                fields=("account", "invoice_number"),
                name="unique_account_invoice_number",
            ),
        ),
    ]
