# Generated by Django 5.2.7 on 2025-11-01 07:40

from decimal import Decimal

from django.db import migrations, models


def populate_profit_margin(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    for product in Product.objects.all():
        sale_price = Decimal(product.sale_price or 0)
        purchase_price = Decimal(product.purchase_price or 0)
        if sale_price > 0:
            margin = (sale_price - purchase_price) / sale_price * Decimal("100")
            product.profit_margin = margin.quantize(Decimal("0.01"))
        else:
            product.profit_margin = Decimal("0.00")
        product.save(update_fields=["profit_margin"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_product_additional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.RunPython(populate_profit_margin, migrations.RunPython.noop),
    ]
